# Description of two models

In that work Weibull models for survival analysis are used.
The first one - is separate Weibull model for only uncensored data.
The second - separate Weibull model for censored data.
Third - hierarchical Weibull model for uncensored data.

At first, the choice was between exponential and weibull model, but 
one of the main cons of the exponential distribution is that it has a 
constant hazard function, that is why it is too simple for that example.

# Weibull Generalised Linear Model

Let $y \sim \text{Weibull}(\alpha, \sigma)$, so that
$$
\text{Weibull}(y|\alpha,\sigma) =
\frac{\alpha}{\sigma} \, \left( \frac{y}{\sigma} \right)^{\alpha - 1}
\, \exp \! \left( \! - \left( \frac{y}{\sigma} \right)^{\alpha}
\right),
$$
for $y \in [0,\infty), \alpha \in \mathbb{R}^+,$ and $\sigma \in \mathbb{R}^+$. 

## Motivating the distribution

The Weibull distribution is often used as a more flexible and complex alternative to the semi-parametric proportional hazard Cox model for modelling time to failure events, since the hazard rate is not taken to be constant with time.

## The Weibull distribution as a member of the exponential family

Now take $\alpha$ fixed and finite, then it can be shown that this distribution belongs to the exponential family since we can write it's probability density function
$$
\text{Weibull}(y|\sigma) ={\alpha y^{\alpha -1}}\exp(-y^{\alpha}\sigma^{-\alpha}-\alpha\log\sigma),
$$
with
\begin{align*}
b(y)&={\alpha y^{\alpha -1}} \\
\eta&=\sigma^{-\alpha}\\
T(y)&=-y^{\alpha} \\
a(\eta)&=\alpha\log\sigma.
\end{align*}

## Defining the link function

Looking at our sufficient statistic $\eta=\sigma^{-\alpha}$, it can be shown that
$$
\sigma=\exp{({\frac{\log\eta}{-\alpha}})}
$$
where we construct $\eta = \exp(\boldsymbol X\beta)$ so that $\eta$ is strictly positive. Thus we choose a log link function for our GLM such that
$$
\sigma = \exp(-\frac{\boldsymbol X\beta}{\alpha}).
$$

## Weibull Survival Model

The density function for Weibull distributed survival times:

$$
{p(t_{i}|\alpha,\lambda_{i}) = \alpha t_{i}^{\alpha-1}\exp{(\lambda_{i}-\exp{\lambda_{i}}t_{i}^{\alpha})}}
$$

It can be rewritten as:

$$
{p(t_{i}|\alpha,\gamma_{i}) = \exp{\bigg(-\bigg(\frac{t_{i}}{\gamma_{i}}\bigg)^{\alpha}\bigg)}\frac{\alpha}{\gamma_{i}}\bigg(\frac{t_{i}}{\gamma_{i}}\bigg)^{\alpha-1}}
$$
, where $\alpha$ - shape, $\gamma$ - scale.

New variable $\lambda$ is created. Connection between $\lambda$ and $\gamma$ is:

$$
{\lambda=-\alpha \log{\gamma}}
$$
The survival function, showing the probability that the death will be after a certain time t, is:

$$
{S(t_{i}|\alpha,\lambda_{i})=\exp(-\exp(\lambda_{i})t_{i}^{\alpha})}
$$
The likelihood of $\alpha$ and $\lambda$ follows the equation below ($v_{i}$ - indicator, showing 0 for censored and 1 - not censored):

$$
{L(\alpha,\lambda|t)=\prod\limits_{i = 1}^n p(t_{i}|\alpha,\lambda_{i})^{v_{i}} S(t_{i}|\alpha,\lambda_{i})^{1-v_{i}}}=
\prod\limits_{i = 1}^n (\alpha t_{i}^{\alpha-1}exp(\lambda_{i}))^{v_{i}}(exp(-exp(\lambda_{i})t_{i}^{\alpha}))
$$

If $\lambda=X\beta$, than log-likelihood function can be expressed like this:

$$
l(\alpha,\beta|t,x)=\sum\limits_{i = 1}^nv_{i}(\log(\alpha)+(\alpha-1)log(t_{i})+X_{i}\beta)-\exp(X_{i}\beta)t_{i}^{\alpha}
$$
If the data is censored, log-likelihood consists only of logarithm of survival function.
In Stan package that can be expressed with weibull_lccdf() function, it corresponds to 
the log of the Weibull complementary cumulative distribution function of y given shape alpha and scale sigma - 
and it is exactly the logarithm of survival function.

For clearness, complementary cumulative distribution function is:
$$
\bar{F}_{X}(x)=P(X>x)=1-F_{X}(x)
$$
, where $F_{X}(x)$ - cumulative distribution function.


# Weibull Survival Hierarchical model

The dataset has the feature, showing the institutional code of each observation.
In total, there are 17 institutions. It is obvious, that in these institutions work different professionals,
the patient care can differ, so it is quite logical to use the hierarchical model for that feature.

The alpha parameter remained the same for all the models, the priors for beta...

# Weakly-informative priors

Weakly-informative priors for parameters are used:
$$
\beta \sim Norm(0,10)
$$

$$
\alpha \sim Gamma(1,1)
$$
From the normal prior formula (especially, variance), we see that there is enough
uncertainty about each parameter, which leads to a weak informative distribution. 
Chosen priors do not contribute strongly to the posterior, so the data can "speak for itself". 

After understanding the mathematical concepts of the Weibull model for Survival analysis, the model can be implemented in Stan.